# Window
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60

# Player
PLAYER_WIDTH = 30
PLAYER_HEIGHT = 40
PLAYER_SPEED = 5
PLAYER_JUMP_STRENGTH = 12
GRAVITY = 0.5

# Platforms
PLATFORM_WIDTH = 100
PLATFORM_HEIGHT = 20

MIN_PLATFORM_VERTICAL_DISTANCE = 80
MAX_PLATFORM_VERTICAL_DISTANCE = 130

MAX_PLATFORM_HORIZONTAL_DISTANCE = 180

# World
INITIAL_PLATFORM_COUNT = 8
PLATFORMS_AHEAD = 5
PLATFORM_CLEANUP_DISTANCE = 700

# Camera
CAMERA_FOLLOW_OFFSET = 200

# Game Over
GAME_OVER_TITLE = "GAME OVER"
GAME_OVER_BUTTON = "RESUME"

GAME_OVER_TITLE_SIZE = 64
GAME_OVER_BUTTON_SIZE = 28